# Generated by Django 2.0 on 2018-01-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prasna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizitem',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Medium'), (0, 'Low'), (2, 'High')], default=0),
        ),
    ]
