# Generated by Django 2.0 on 2018-01-06 02:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prasna', '0002_auto_20180101_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(upload_to='')),
                ('type', models.CharField(choices=[('Image', 'Image'), ('Audio', 'Audio'), ('Video', 'Video')], max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='quizitem',
            options={'verbose_name_plural': 'Quiz items'},
        ),
        migrations.RemoveField(
            model_name='quizitem',
            name='a_media_url',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='quizitem',
            name='a_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_images', to='prasna.Media'),
        ),
        migrations.AlterField(
            model_name='quizitem',
            name='difficulty',
            field=models.IntegerField(choices=[(2, 'High'), (0, 'Low'), (1, 'Medium')], default=0),
        ),
        migrations.AlterField(
            model_name='quizitem',
            name='q_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q_images', to='prasna.Media'),
        ),
        migrations.AddField(
            model_name='quizitem',
            name='q_audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q_audios', to='prasna.Media'),
        ),
        migrations.AddField(
            model_name='quizitem',
            name='q_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q_videos', to='prasna.Media'),
        ),
    ]
