# Generated by Django 2.0 on 2018-01-10 06:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prasna', '0003_auto_20180106_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizitem',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=10),
        ),
        migrations.AlterField(
            model_name='quizitem',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0),
        ),
    ]
